/**
* Inventory of Depression and Anxiety Symptoms
*
* Watson, D., O’Hara, M. W., Naragon-Gainey, K., Koffel, E., Chmielewski, M.,
* Kotov, R., ... & Ruggero, C. J. (2012). Development and validation of new
* anxiety and bipolar symptom scales for an expanded version of the IDAS
* (the IDAS-II). Assessment, 19(4), 399-420.
*
**/

var idas = {
  type: jsPsychSurveyTemplate,
  items: [
    "I blamed myself for things",
    "I felt depressed",
    "I felt discouraged about things",
    "I felt fidgety, restless",
    "I felt inadequate",
    "I found myself worrying all the time",
    "I had little interest in my usual hobbies and activities",
    "I had trouble concentrating",
    "I had trouble making up my mind",
    "I talked more slowly than usual",
    "I felt elated for no special reason",
    'I felt like I was "on top of the world"',
    "I felt that I could do things that other people couldn't",
    "I had much more energy than usual",
    "I had so much energy it was hard for me to sit still",
    "I kept racing from one activity to the next",
    "I spoke so rapidly that others could not understand me",
    'It felt like my mind was moving "a mile a minute"',
    "My thoughts jumped rapidly from one idea to another",
    "My thoughts were moving so quickly it was hard to keep up",
    "I had trouble falling asleep",
    "I slept less than usual",
    "I slept very poorly",
    "I woke up early and could not get back to sleep",
    "I woke up frequently during the night",
    "I woke up much earlier than usual",
    "I felt drowsy, sleepy",
    "I felt exhausted",
    "I felt much worse in the morning than later in the day",
    "I had trouble waking up in the morning",
    "I slept more than usual",
    "It took a lot of effort for me to get going",
    "I checked things over and over again",
    "I felt the urge to check to make sure I had done something",
    "I found myself checking things, even though I knew it wasn't necessary",
    "I avoided handling dirty things",
    "I avoided using public restrooms",
    "I had difficulty touching something that was dirty",
    "I had to clean myself because I felt contaminated",
    "I used an object (such as a towel) so I could avoid touching something directly",
    "I washed my hands excessively",
    "I worried a lot about germs",
    "I felt compelled to follow certain rituals",
    'I felt the urge to rearrange things so that they were "just right"',
    "I followed the same, fixed order in performing everyday tasks",
    "I had little rituals or habits that took up a lot of my time",
    "I rearranged things so that they were in a certain order",
    "I felt a pain in my chest",
    "I felt dizzy or lightheaded",
    "I felt faint",
    "I felt like I was choking",
    "I had a very dry mouth",
    "I was short of breath",
    "I was trembling or shaking",
    "My heart was racing or pounding",
    "I became anxious in a crowded public setting",
    "I felt self-conscious knowing that others were watching me",
    "I found it difficult to make eye contact with people",
    "I found it difficult to talk with people I did not know well",
    "I was anxious about talking in public",
    "I was worried about embarrassing myself socially",
    "I avoided situations that bring up bad memories",
    "I avoided talking about bad experiences from my past",
    "I tried not to think about bad things from my past",
    "I tried to ignore upsetting memories",
    "I got upset thinking about something bad that happened",
    "I had disturbing thoughts of something bad that happened to me",
    "I had memories of something scary that happened",
    "I had nightmares that reminded me of something bad that happened",
    "I ate more than usual",
    "I ate when I wasn't hungry",
    "I thought a lot about food",
    "I did not feel much like eating",
    "I did not have much of an appetite",
    "I felt like eating less than usual",
    "I felt enraged",
    "I felt like breaking things",
    "I lost my temper and yelled at people",
    "I was furious",
    "Little things made me mad"
  ],
  scale: [
    "Not at all",
    "A little bit",
    "Moderately",
    "Quite a bit",
    "Extremely"
  ],
  reverse: [
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
  ],
  instructions: "Below is a list of feelings, sensations, problems, and experiences that people sometimes have. Read each item to determine how well it describes your recent feelings and experiences during the past two weeks, including today.",
  survey_width: 950,
  item_width: 45,
  scale_repeat: 8,
}
